### ISSUE TITLE
Comparing two float vectors

### ISSUE THREAD

**Issue by BlurryLight** [g1n0st/AyaMath#1]
https://github.com/g1n0st/AyaMath/blob/0e6894b4e75d02e0247569454cdd08424be7cdfa/src/Vector3.h#L185

是否应该使用epsilon来比较而不是直接判等浮点数？不是很确定，我看pbrt里面也是直接判等的。

**Comment by g1n0st** [comment]
因为除了直接拷贝内存的比较（我用在模型的读取里），数值上的比较一般不会直接用这个运算符，一般都是向量归一化后用点乘来算cos角度比较，这里就可以引入eps了。
